name: Haskell CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  stack:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Setup Haskell Stack
      uses: haskell-actions/setup@v2
      with:
        enable-stack: true

    - name: Cache ~/.stack
      uses: actions/cache@v5
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack

    - name: Cache .stack-work
      uses: actions/cache@v5
      with:
        path: .stack-work
        key: ${{ runner.os }}-stack-work


    - name: Install dependencies
      run: |
        stack build --only-dependencies

    - name: Build
      run: |
        stack build

    - name: Test
      run: |
        stack test
